name = "hugo-multi-bootswatch"
license = "MIT"
licenselink = "http://sm.mit-license.org/"
description = "Hugo BootSwatch Theme is a single column theme for [hugo](http://hugo.spf13.com/) based on [Twitter Bootstrap](http://getbootstrap.com/) and a css styling from [Bootswatch](http://bootswatch.com/)."
tags = ["post", "category"]
min_version = 0.14

[author]
    name = "Marco Pas"
    email = "marco.pasopas@gmail.com"
